"""initial quality harness schema

Revision ID: 3b92e7aa7d28
Revises:
Create Date: 2026-08-21 22:31:50.007312
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "3b92e7aa7d28"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eval_datasets",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("split", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_eval_datasets_name_version"),
    )
    op.create_table(
        "evaluation_targets",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "target_kind",
            sa.Enum("agent", "tool", name="target_kind", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "protocol",
            sa.Enum(
                "http",
                "sse",
                "ag_ui",
                "a2a",
                "mcp",
                name="target_protocol",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("auth_ref", sa.Text(), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "capabilities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(target_kind = 'agent' "
            "AND protocol IN ('http', 'sse', 'ag_ui', 'a2a')) "
            "OR (target_kind = 'tool' AND protocol = 'mcp')",
            name="ck_evaluation_targets_kind_protocol",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "gate_policies",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column(
            "thresholds",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_gate_policies_name_version"),
    )
    op.create_table(
        "pricing_snapshots",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "prices",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "model", "version", name="uq_pricing_snapshots_provider_model_version"
        ),
    )
    op.create_table(
        "agent_versions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("tool_schema_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["target_id"], ["evaluation_targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_id", "version", name="uq_agent_versions_target_version"),
    )
    op.create_index(
        op.f("ix_agent_versions_target_id"), "agent_versions", ["target_id"], unique=False
    )
    op.create_table(
        "eval_cases",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("dataset_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "input_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "expected",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["eval_datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "external_id", name="uq_eval_cases_dataset_external"),
        sa.UniqueConstraint("dataset_id", "sha256", name="uq_eval_cases_dataset_hash"),
    )
    op.create_index(op.f("ix_eval_cases_dataset_id"), "eval_cases", ["dataset_id"], unique=False)
    op.create_table(
        "eval_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("dataset_id", sa.BigInteger(), nullable=False),
        sa.Column("baseline_version_id", sa.BigInteger(), nullable=True),
        sa.Column("candidate_version_id", sa.BigInteger(), nullable=False),
        sa.Column("replay_of_run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "cancel_requested",
                "cancelled",
                "completed",
                "failed",
                name="run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expected_case_count", sa.Integer(), nullable=False),
        sa.Column("completed_case_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_case_count >= 0 AND expected_case_count >= completed_case_count",
            name="ck_eval_runs_case_counts",
        ),
        sa.ForeignKeyConstraint(
            ["baseline_version_id"], ["agent_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["candidate_version_id"], ["agent_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["eval_datasets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["replay_of_run_id"], ["eval_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_eval_runs_active_created",
        "eval_runs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'running', 'cancel_requested')"),
    )
    op.create_index(
        op.f("ix_eval_runs_baseline_version_id"), "eval_runs", ["baseline_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_eval_runs_candidate_version_id"),
        "eval_runs",
        ["candidate_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_eval_runs_dataset_id"), "eval_runs", ["dataset_id"], unique=False)
    op.create_index(
        op.f("ix_eval_runs_replay_of_run_id"), "eval_runs", ["replay_of_run_id"], unique=False
    )
    op.create_index(
        "ix_eval_runs_status_created", "eval_runs", ["status", "created_at"], unique=False
    )
    op.create_table(
        "case_results",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "version_role",
            sa.Enum(
                "baseline",
                "candidate",
                name="version_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "output",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column(
            "scores",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("failure_type", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["eval_cases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["eval_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "case_id", "version_role", "attempt", name="uq_case_results_attempt"
        ),
    )
    op.create_index(op.f("ix_case_results_case_id"), "case_results", ["case_id"], unique=False)
    op.create_index(op.f("ix_case_results_run_id"), "case_results", ["run_id"], unique=False)
    op.create_index(
        "ix_case_results_run_role", "case_results", ["run_id", "version_role"], unique=False
    )
    op.create_index(op.f("ix_case_results_trace_id"), "case_results", ["trace_id"], unique=False)
    op.create_table(
        "gate_results",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("policy_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "ship",
                "warn",
                "block",
                name="gate_decision",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metric_deltas",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["policy_id"], ["gate_policies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["eval_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index(op.f("ix_gate_results_policy_id"), "gate_results", ["policy_id"], unique=False)
    op.create_table(
        "usage_measurements",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("case_result_id", sa.BigInteger(), nullable=False),
        sa.Column("pricing_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "measurement_status",
            sa.Enum(
                "known",
                "partial",
                "unknown",
                name="measurement_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("output_tokens", sa.BigInteger(), nullable=True),
        sa.Column("cache_read_tokens", sa.BigInteger(), nullable=True),
        sa.Column("cache_write_tokens", sa.BigInteger(), nullable=True),
        sa.Column("reasoning_tokens", sa.BigInteger(), nullable=True),
        sa.Column("embedding_tokens", sa.BigInteger(), nullable=True),
        sa.Column("vision_tokens", sa.BigInteger(), nullable=True),
        sa.Column("judge_tokens", sa.BigInteger(), nullable=True),
        sa.Column("model_cost", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("external_tool_cost", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column(
            "raw_usage",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0", name="ck_usage_input_tokens"
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0", name="ck_usage_output_tokens"
        ),
        sa.ForeignKeyConstraint(["case_result_id"], ["case_results.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["pricing_snapshot_id"], ["pricing_snapshots.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_result_id"),
    )
    op.create_index(
        op.f("ix_usage_measurements_pricing_snapshot_id"),
        "usage_measurements",
        ["pricing_snapshot_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_usage_measurements_pricing_snapshot_id"), table_name="usage_measurements"
    )
    op.drop_table("usage_measurements")
    op.drop_index(op.f("ix_gate_results_policy_id"), table_name="gate_results")
    op.drop_table("gate_results")
    op.drop_index(op.f("ix_case_results_trace_id"), table_name="case_results")
    op.drop_index("ix_case_results_run_role", table_name="case_results")
    op.drop_index(op.f("ix_case_results_run_id"), table_name="case_results")
    op.drop_index(op.f("ix_case_results_case_id"), table_name="case_results")
    op.drop_table("case_results")
    op.drop_index("ix_eval_runs_status_created", table_name="eval_runs")
    op.drop_index(op.f("ix_eval_runs_replay_of_run_id"), table_name="eval_runs")
    op.drop_index(op.f("ix_eval_runs_dataset_id"), table_name="eval_runs")
    op.drop_index(op.f("ix_eval_runs_candidate_version_id"), table_name="eval_runs")
    op.drop_index(op.f("ix_eval_runs_baseline_version_id"), table_name="eval_runs")
    op.drop_index(
        "ix_eval_runs_active_created",
        table_name="eval_runs",
        postgresql_where=sa.text("status IN ('queued', 'running', 'cancel_requested')"),
    )
    op.drop_table("eval_runs")
    op.drop_index(op.f("ix_eval_cases_dataset_id"), table_name="eval_cases")
    op.drop_table("eval_cases")
    op.drop_index(op.f("ix_agent_versions_target_id"), table_name="agent_versions")
    op.drop_table("agent_versions")
    op.drop_table("pricing_snapshots")
    op.drop_table("gate_policies")
    op.drop_table("evaluation_targets")
    op.drop_table("eval_datasets")
    # ### end Alembic commands ###
