"""multi tenant auth and administration

Revision ID: b51a1e5e9a78
Revises: d6800930fdf6
Create Date: 2026-08-22 18:23:16.438410
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "b51a1e5e9a78"
down_revision: str | Sequence[str] | None = "d6800930fdf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    connection = op.get_bind()
    default_organization_id = connection.execute(
        sa.text(
            "INSERT INTO organizations (slug, name, active) "
            "VALUES ('default', 'Default Organization', true) RETURNING id"
        )
    ).scalar_one()
    op.create_table(
        "permissions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("platform_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "password_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=True),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_logs_org_created", "audit_logs", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("family_id", sa.String(length=64), nullable=False),
        sa.Column("refresh_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_session_id", sa.BigInteger(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_session_id"], ["auth_sessions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_hash"),
    )
    op.create_index(
        op.f("ix_auth_sessions_family_id"), "auth_sessions", ["family_id"], unique=False
    )
    op.create_index(
        "ix_auth_sessions_user_active", "auth_sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_memberships_org_user"),
    )
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_roles_org_name"),
    )
    op.create_index(op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False)
    op.create_table(
        "service_accounts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_service_accounts_org_name"),
    )
    op.create_index(
        op.f("ix_service_accounts_organization_id"),
        "service_accounts",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "system_settings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=True),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "key", name="uq_system_settings_scope_key"),
    )
    op.create_index(
        op.f("ix_system_settings_organization_id"),
        "system_settings",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("service_account_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("prefix", sa.String(length=20), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_account_id"], ["service_accounts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(op.f("ix_api_keys_prefix"), "api_keys", ["prefix"], unique=False)
    op.create_index(
        op.f("ix_api_keys_service_account_id"), "api_keys", ["service_account_id"], unique=False
    )
    op.create_table(
        "membership_roles",
        sa.Column("membership_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["membership_id"], ["memberships.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("membership_id", "role_id"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("permission_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    permission_rows = [
        ("target:read", "Read targets"),
        ("target:manage", "Manage targets"),
        ("dataset:read", "Read datasets"),
        ("dataset:manage", "Manage datasets"),
        ("run:read", "Read evaluation runs"),
        ("run:execute", "Execute and control evaluation runs"),
        ("gate:read", "Read release gates"),
        ("gate:manage", "Manage release gate policies"),
        ("usage:read", "Read usage and cost"),
        ("trace:read", "Read trace and failure data"),
        ("member:manage", "Manage organization members"),
        ("role:manage", "Manage roles and permissions"),
        ("service_account:manage", "Manage service accounts and API keys"),
        ("audit:read", "Read audit logs"),
        ("setting:manage", "Manage organization settings"),
        ("demo:bootstrap", "Create demo fixtures"),
    ]
    for code, name in permission_rows:
        connection.execute(
            sa.text("INSERT INTO permissions (code, name, description) VALUES (:code, :name, '')"),
            {"code": code, "name": name},
        )
    role_permissions = {
        "Administrator": [code for code, _ in permission_rows],
        "Evaluator": [
            "target:read",
            "dataset:read",
            "run:read",
            "run:execute",
            "gate:read",
            "usage:read",
            "trace:read",
        ],
        "Viewer": [
            "target:read",
            "dataset:read",
            "run:read",
            "gate:read",
            "usage:read",
            "trace:read",
        ],
    }
    for role_name, codes in role_permissions.items():
        role_id = connection.execute(
            sa.text(
                "INSERT INTO roles "
                "(organization_id, name, description, system) "
                "VALUES (:organization_id, :name, :description, true) RETURNING id"
            ),
            {
                "organization_id": default_organization_id,
                "name": role_name,
                "description": f"Built-in {role_name.lower()} role",
            },
        ).scalar_one()
        connection.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) "
                "SELECT :role_id, id FROM permissions WHERE code = ANY(:codes)"
            ),
            {"role_id": role_id, "codes": codes},
        )
    tenant_tables = (
        "eval_datasets",
        "eval_runs",
        "evaluation_targets",
        "gate_policies",
        "pricing_snapshots",
    )
    for table_name in tenant_tables:
        op.add_column(table_name, sa.Column("organization_id", sa.BigInteger(), nullable=True))
        connection.execute(
            sa.text(f"UPDATE {table_name} SET organization_id = :organization_id"),
            {"organization_id": default_organization_id},
        )
        op.alter_column(table_name, "organization_id", nullable=False)
    op.drop_constraint(op.f("uq_eval_datasets_name_version"), "eval_datasets", type_="unique")
    op.create_index(
        op.f("ix_eval_datasets_organization_id"), "eval_datasets", ["organization_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_eval_datasets_org_name_version", "eval_datasets", ["organization_id", "name", "version"]
    )
    op.create_foreign_key(
        "eval_datasets_organization_id_fkey",
        "eval_datasets",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_eval_runs_organization_id"), "eval_runs", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        "eval_runs_organization_id_fkey",
        "eval_runs",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("evaluation_targets_name_key"), "evaluation_targets", type_="unique")
    op.create_index(
        op.f("ix_evaluation_targets_organization_id"),
        "evaluation_targets",
        ["organization_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_evaluation_targets_org_name", "evaluation_targets", ["organization_id", "name"]
    )
    op.create_foreign_key(
        "evaluation_targets_organization_id_fkey",
        "evaluation_targets",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("uq_gate_policies_name_version"), "gate_policies", type_="unique")
    op.create_index(
        op.f("ix_gate_policies_organization_id"), "gate_policies", ["organization_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_gate_policies_org_name_version", "gate_policies", ["organization_id", "name", "version"]
    )
    op.create_foreign_key(
        "gate_policies_organization_id_fkey",
        "gate_policies",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("uq_pricing_snapshots_provider_model_version"), "pricing_snapshots", type_="unique"
    )
    op.create_index(
        op.f("ix_pricing_snapshots_organization_id"),
        "pricing_snapshots",
        ["organization_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_pricing_snapshots_org_provider_model_version",
        "pricing_snapshots",
        ["organization_id", "provider", "model", "version"],
    )
    op.create_foreign_key(
        "pricing_snapshots_organization_id_fkey",
        "pricing_snapshots",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "pricing_snapshots_organization_id_fkey", "pricing_snapshots", type_="foreignkey"
    )
    op.drop_constraint(
        "uq_pricing_snapshots_org_provider_model_version", "pricing_snapshots", type_="unique"
    )
    op.drop_index(op.f("ix_pricing_snapshots_organization_id"), table_name="pricing_snapshots")
    op.create_unique_constraint(
        op.f("uq_pricing_snapshots_provider_model_version"),
        "pricing_snapshots",
        ["provider", "model", "version"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("pricing_snapshots", "organization_id")
    op.drop_constraint("gate_policies_organization_id_fkey", "gate_policies", type_="foreignkey")
    op.drop_constraint("uq_gate_policies_org_name_version", "gate_policies", type_="unique")
    op.drop_index(op.f("ix_gate_policies_organization_id"), table_name="gate_policies")
    op.create_unique_constraint(
        op.f("uq_gate_policies_name_version"),
        "gate_policies",
        ["name", "version"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("gate_policies", "organization_id")
    op.drop_constraint(
        "evaluation_targets_organization_id_fkey",
        "evaluation_targets",
        type_="foreignkey",
    )
    op.drop_constraint("uq_evaluation_targets_org_name", "evaluation_targets", type_="unique")
    op.drop_index(op.f("ix_evaluation_targets_organization_id"), table_name="evaluation_targets")
    op.create_unique_constraint(
        op.f("evaluation_targets_name_key"),
        "evaluation_targets",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("evaluation_targets", "organization_id")
    op.drop_constraint("eval_runs_organization_id_fkey", "eval_runs", type_="foreignkey")
    op.drop_index(op.f("ix_eval_runs_organization_id"), table_name="eval_runs")
    op.drop_column("eval_runs", "organization_id")
    op.drop_constraint("eval_datasets_organization_id_fkey", "eval_datasets", type_="foreignkey")
    op.drop_constraint("uq_eval_datasets_org_name_version", "eval_datasets", type_="unique")
    op.drop_index(op.f("ix_eval_datasets_organization_id"), table_name="eval_datasets")
    op.create_unique_constraint(
        op.f("uq_eval_datasets_name_version"),
        "eval_datasets",
        ["name", "version"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("eval_datasets", "organization_id")
    op.drop_table("role_permissions")
    op.drop_table("membership_roles")
    op.drop_index(op.f("ix_api_keys_service_account_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_prefix"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_system_settings_organization_id"), table_name="system_settings")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_service_accounts_organization_id"), table_name="service_accounts")
    op.drop_table("service_accounts")
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index("ix_auth_sessions_user_active", table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_family_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_org_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("permissions")
    op.drop_table("organizations")
    # ### end Alembic commands ###
